version: "3"
services:
  node:
    container_name: "totaljs_example"
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8000"
    command: "npm start"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M